""" The technical slide deck for phases 1-3 (phase 3, prompt 12).

Writes ``docs/slides/technical_summary.pptx`` (16:9) from figures already
generated by this repository's scripts, plus one new schematic drawn here
(``docs/figs/fig_slides_pipeline.png``).  Every number on a slide is taken
from the committed tables where it can be (the velocity tables, the Keplerian
residuals, the prompt-9 variants); the rest are quoted from the Reports in
``claude_prompts/data_phase{1,2,3}_prompt.md``.

Which script makes which figure:

    figs_phase1.py          fig_p1_*
    figs_phase2.py          fig_p2_*
    deconvolve_template.py  fig_p3_deconv
    fit_one_chunk.py        fig_p4_one_chunk
    fit_one_epoch.py        fig_p5_one_epoch
    compare_lsf_models.py   fig_p6_lsf_models
    fit_bstars.py           fig_p6b_bstars
    fit_all_epochs.py       fig_p7_epochs
    figs_phase3.py          fig_ph3_*
    diagnose_phase3.py      fig_p9_diagnosis
    figs.py                 fig7_three_ways, fig8_precision
    make_slides.py          fig_slides_pipeline

Run with:

    conda run -n pypeit14 python -m first_hires_exoplanet.make_slides

"""

# Standard imports
import os
import argparse

import numpy as np
from astropy.table import Table
from PIL import Image

import matplotlib
matplotlib.use('Agg')
from matplotlib import pyplot as plt
from matplotlib.patches import FancyBboxPatch

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(_HERE)
DATA = os.path.join(_HERE, 'data')
FIGS = os.path.join(ROOT, 'docs', 'figs')
OUT = os.path.join(ROOT, 'docs', 'slides', 'technical_summary.pptx')

# House palette (figs.py, figs_phase2.py)
BLUE, ORANGE, AQUA = '2a78d6', 'eb6834', '1baf7a'
INK, INK2, RULE = '0b0b0b', '52514e', 'c9c8c3'
W, H = Inches(13.333), Inches(7.5)


def rgb(hexstr):
    return RGBColor.from_string(hexstr)


# ---------------------------------------------------------------------------
# Numbers, from the committed tables
# ---------------------------------------------------------------------------

def numbers():
    vt = Table.read(os.path.join(DATA, 'iodine_velocities.csv'))
    kr = Table.read(os.path.join(DATA, 'iodine_keplerian_residuals.csv'))
    var = Table.read(os.path.join(DATA, 'diagnose_variants.csv'))
    xc = Table.read(os.path.join(DATA, 'xcorr_velocities.csv'))
    from first_hires_exoplanet import figs_phase2 as f2
    t = np.asarray(vt['jd'], float)
    fo = f2.fit_circular(t, np.asarray(vt['v_bary'], float))
    base = var[var['variant'] == 'prompt 7 (all)'][0]
    best = var[var['variant'] == 'both'][0]
    return dict(n_epochs=len(vt), n_nights=len(set(vt['night'])),
                K=fo['K'], sK=fo['sigma_K'], nsig=fo['K'] / fo['sigma_K'],
                resid=float(np.std(kr['resid'], ddof=1)),
                sig_epoch=float(np.median(vt['sig_epoch'])),
                sig_phot=float(np.median(vt['sig_photon'])),
                chunks=int(np.sum(vt['n_chunks'])), good=int(np.sum(vt['n_good'])),
                xc_rms=float(np.std(xc['v_rel'], ddof=1)), n_xc=len(xc),
                var_base=float(base['resid_rms']), var_best=float(best['resid_rms']),
                K_best=float(best['K']), sK_best=float(best['sigma_K']))


# ---------------------------------------------------------------------------
# The one new figure: the pipeline, phase by phase
# ---------------------------------------------------------------------------

def fig_pipeline(outfile):
    fig, ax = plt.subplots(figsize=(13., 4.2))
    ax.set_xlim(0, 13)
    ax.set_ylim(0, 4.2)
    ax.axis('off')
    cols = {1: '#' + AQUA, 2: '#8a8a86', 3: '#' + BLUE}
    boxes = [
        (0.2, 'KOA raw frames\n36 science, 20 nights\n1997-12 to 1998-09', None),
        (2.75, 'PypeIt\nkeck_hires_orig\n+ 6 source fixes', 1),
        (5.3, '37-order spec1d\nwavecal RMS\n0.11-0.15 px', 1),
        (7.85, 'phase 2: ThAr +\ncross-correlation\n702 m/s', 2),
        (7.85, 'phase 3: pyodine fork\niodine forward model\n26 m/s', 3),
        (10.4, 'K = 72.4 ± 7.1 m/s\n10.2σ, P found blind', 3),
    ]
    ys = [1.5, 1.5, 1.5, 2.65, 0.35, 0.35]
    for (x, text, ph), y in zip(boxes, ys):
        c = cols.get(ph, '#0b0b0b')
        ax.add_patch(FancyBboxPatch((x, y), 2.3, 1.2, boxstyle='round,pad=0.04,rounding_size=0.12',
                                    fc='white', ec=c, lw=2.0))
        ax.text(x + 1.15, y + 0.6, text, ha='center', va='center', fontsize=11.5, color='#0b0b0b')
    arrow = dict(arrowstyle='-|>', color='#52514e', lw=1.4)
    ax.annotate('', xy=(2.72, 2.1), xytext=(2.52, 2.1), arrowprops=arrow)
    ax.annotate('', xy=(5.27, 2.1), xytext=(5.07, 2.1), arrowprops=arrow)
    ax.annotate('', xy=(7.82, 3.25), xytext=(7.62, 2.4), arrowprops=arrow)
    ax.annotate('', xy=(7.82, 0.95), xytext=(7.62, 1.8), arrowprops=arrow)
    ax.annotate('', xy=(10.37, 0.95), xytext=(10.17, 0.95), arrowprops=arrow)
    ax.text(10.4 + 1.15, 3.25, 'not a detection\n(K = 408 ± 188 m/s)', ha='center', va='center',
            fontsize=11, color='#8a8a86')
    ax.annotate('', xy=(10.4, 3.25), xytext=(10.17, 3.25), arrowprops=dict(arrowstyle='-|>',
                                                                            color='#8a8a86', lw=1.2))
    ax.text(0.2, 4.05, 'phase 1', color=cols[1], fontsize=12, weight='bold', va='top')
    ax.text(1.2, 4.05, 'phase 2', color=cols[2], fontsize=12, weight='bold', va='top')
    ax.text(2.2, 4.05, 'phase 3', color=cols[3], fontsize=12, weight='bold', va='top')
    fig.savefig(outfile, dpi=160, bbox_inches='tight', facecolor='white')
    plt.close(fig)
    print('  wrote {:s}'.format(outfile))


# ---------------------------------------------------------------------------
# Slide helpers
# ---------------------------------------------------------------------------

#: Prompt 13: no text on any slide is smaller than this
MIN_PT = 20


def _pt(size):
    """ Every font size goes through here, so none falls below MIN_PT. """
    return Pt(max(int(size), MIN_PT))


class Deck:

    def __init__(self):
        self.prs = Presentation()
        self.prs.slide_width, self.prs.slide_height = W, H
        self.blank = self.prs.slide_layouts[6]
        self.n = 0

    def _text(self, slide, x, y, w, h, paras, size=MIN_PT, color=INK, bold=False, align=None):
        box = slide.shapes.add_textbox(x, y, w, h)
        tf = box.text_frame
        tf.word_wrap = True
        for i, p in enumerate(paras):
            para = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
            txt, kw = p if isinstance(p, tuple) else (p, {})
            level = kw.get('level', 0)
            bullet = kw.get('bullet', False)
            run = para.add_run()
            run.text = ('• ' if bullet and level == 0 else '– ' if bullet else '') + txt
            run.font.size = _pt(kw.get('size', size))
            run.font.bold = kw.get('bold', bold)
            run.font.color.rgb = rgb(kw.get('color', color))
            para.level = level
            para.space_after = Pt(kw.get('space', 8))
            if align:
                para.alignment = align
        return box

    def _chrome(self, slide, title):
        """ Title bar and slide number (the 10-pt running footer is gone: prompt 13). """
        self.n += 1
        bar = slide.shapes.add_shape(1, 0, 0, W, Inches(0.09))
        bar.fill.solid()
        bar.fill.fore_color.rgb = rgb(BLUE)
        bar.line.fill.background()
        self._text(slide, Inches(0.55), Inches(0.25), Inches(11.6), Inches(0.9),
                   [(title, dict(size=30, bold=True))])
        self._text(slide, Inches(12.0), Inches(0.3), Inches(0.9), Inches(0.5),
                   [(str(self.n), dict(color=INK2))], align=PP_ALIGN.RIGHT)

    def _image(self, slide, path, x, y, w, h):
        """ Fit an image inside a box, preserving its aspect ratio, centred. """
        with Image.open(path) as im:
            iw, ih = im.size
        scale = min(w / iw, h / ih)
        pw, ph = int(iw * scale), int(ih * scale)
        slide.shapes.add_picture(path, x + (w - pw) // 2, y + (h - ph) // 2, pw, ph)

    def title(self, title, subtitle, byline):
        s = self.prs.slides.add_slide(self.blank)
        self.n += 1
        bar = s.shapes.add_shape(1, 0, 0, W, Inches(0.12))
        bar.fill.solid()
        bar.fill.fore_color.rgb = rgb(BLUE)
        bar.line.fill.background()
        self._text(s, Inches(0.8), Inches(2.0), Inches(11.7), Inches(1.6),
                   [(title, dict(size=40, bold=True))])
        self._text(s, Inches(0.8), Inches(3.7), Inches(11.7), Inches(1.2),
                   [(subtitle, dict(size=24, color=INK2))])
        self._text(s, Inches(0.8), Inches(5.5), Inches(11.7), Inches(0.8),
                   [(byline, dict(color=INK2))])

    def section(self, label, title, lead, color=BLUE):
        s = self.prs.slides.add_slide(self.blank)
        self.n += 1
        self._text(s, Inches(0.8), Inches(2.3), Inches(11.7), Inches(0.6),
                   [(label, dict(size=22, bold=True, color=color))])
        self._text(s, Inches(0.8), Inches(2.9), Inches(11.7), Inches(1.2),
                   [(title, dict(size=38, bold=True))])
        self._text(s, Inches(0.8), Inches(4.2), Inches(11.5), Inches(2.0),
                   [(lead, dict(size=22, color=INK2))])

    def bullets(self, title, items, takeaway=None, size=22):
        s = self.prs.slides.add_slide(self.blank)
        self._chrome(s, title)
        bottom = TAKE_TOP if takeaway else Inches(7.2)
        self._text(s, Inches(0.7), Inches(1.3), Inches(12.0), bottom - Inches(1.4), items, size=size)
        if takeaway:
            self._takeaway(s, takeaway)
        return s

    def figure(self, title, fig, takeaway=None):
        s = self.prs.slides.add_slide(self.blank)
        self._chrome(s, title)
        top = Inches(1.2)
        bottom = TAKE_TOP - Inches(0.1) if takeaway else Inches(7.3)
        self._image(s, os.path.join(FIGS, fig), Inches(0.4), top, Inches(12.53), bottom - top)
        if takeaway:
            self._takeaway(s, takeaway)
        return s

    def table(self, title, header, rows, takeaway=None, widths=None, row_h=0.62):
        s = self.prs.slides.add_slide(self.blank)
        self._chrome(s, title)
        nr, nc = len(rows) + 1, len(header)
        shp = s.shapes.add_table(nr, nc, Inches(0.5), Inches(1.35), Inches(12.33), Inches(row_h) * nr)
        tbl = shp.table
        if widths:
            for j, wv in enumerate(widths):
                tbl.columns[j].width = Inches(wv)
        for i in range(nr):
            tbl.rows[i].height = Inches(row_h)
        for j, h in enumerate(header):
            self._cell(tbl.cell(0, j), h, BLUE, 'ffffff', True)
        for i, row in enumerate(rows, start=1):
            for j, val in enumerate(row):
                self._cell(tbl.cell(i, j), str(val), 'f3f3f1' if i % 2 else 'ffffff', INK, False)
        if takeaway:
            self._takeaway(s, takeaway)
        return s

    @staticmethod
    def _cell(c, text, fill, color, bold):
        c.text = text
        c.fill.solid()
        c.fill.fore_color.rgb = rgb(fill)
        c.margin_top = c.margin_bottom = Inches(0.04)
        for p in c.text_frame.paragraphs:
            for r in p.runs:
                r.font.size, r.font.bold = _pt(MIN_PT), bold
                r.font.color.rgb = rgb(color)

    def _takeaway(self, slide, text):
        box = slide.shapes.add_shape(1, Inches(0.4), TAKE_TOP, Inches(12.53), Inches(7.35) - TAKE_TOP)
        box.fill.solid()
        box.fill.fore_color.rgb = rgb('eef4fc')
        box.line.fill.background()
        tf = box.text_frame
        tf.word_wrap = True
        r = tf.paragraphs[0].add_run()
        r.text = text
        r.font.size, r.font.bold = _pt(MIN_PT), True
        r.font.color.rgb = rgb(INK)

    def save(self, path):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        self.prs.save(path)
        print('  wrote {:s} ({:d} slides)'.format(path, self.n))


#: Top of the takeaway bar: room for two lines at 20 pt
TAKE_TOP = Inches(6.35)


def B(text, level=0, **kw):
    """ A bullet paragraph. """
    kw.update(bullet=True, level=level)
    return (text, kw)


# ---------------------------------------------------------------------------
# The deck
# ---------------------------------------------------------------------------

def build(out):
    N = numbers()
    fig_pipeline(os.path.join(FIGS, 'fig_slides_pipeline.png'))
    d = Deck()

    d.title('Re-detecting HD 187123 b from the 1998 Keck/HIRES frames',
            'A modern, open reduction of the first planet Keck found: PypeIt + an iodine forward model',
            'J. Xavier Prochaska and Claude  ·  phases 1–3  ·  30 September 2026')

    d.bullets('The bottom line', [
        B('Planet recovered: K = {:.1f} ± {:.1f} m/s ({:.1f}σ); published 72, modern catalogue 69.2'.format(
            N['K'], N['sK'], N['nsig'])),
        B('Period found blind: 3.0954 d (true 3.0966 d), false-alarm probability 2 × 10⁻¹¹'),
        B('{:.1f} m/s per epoch about the orbit; {:d} cell-in epochs, {:d} nights'.format(
            N['resid'], N['n_epochs'], N['n_nights'])),
        B('28× better than lamp-calibrated velocities; ~9× short of Butler’s 3 m/s; '
          '~12× short of the modern pipeline (2.2 m/s)'),
        B('All open: PypeIt + a tested pyodine fork; nothing from the discovery pipeline'),
    ], takeaway='Success criterion (50 m/s per epoch, an independent detection): met.')

    d.figure('Three phases, one chain', 'fig_slides_pipeline.png',
             takeaway='Phase 2 measured why lamps fail; phase 3 replaced the lamp with the iodine cell.')

    # ---- Phase 1 ----------------------------------------------------------
    d.section('Phase 1', 'PypeIt on the pre-2004 HIRES CCD',
              'Can a modern open pipeline reduce the original Tektronix-detector frames at all?',
              color=AQUA)
    d.table('Phase 1: what PypeIt needed', ['item', 'fix', 'symptom'], [
        ['get_rawimage', 'prepix × namp', 'image 21 columns off'],
        ['bad-pixel mask', 'column C − PREPIX', 'mask 20 px off'],
        ['binning', "'1,2' not '2,1'", 'platescale halved'],
        ['check_spectrograph', 'raise the error', 'silently accepted'],
        ['exprng', '[1, None] for Orig', 'science excluded'],
        ['find_trim_edge, sky', '1,1; no sky fit', 'star fills the slit'],
        ['flats', 'borrow clean B1 flats', 'none on most nights'],
    ], widths=[3.3, 4.6, 4.43], row_h=0.56,
        takeaway='Fixes on branch orig-hires-fixes (017bece06); verify_orig_fixes.py reproduces them.')
    d.figure('37 orders, every one solved below 0.2 px', 'fig_p1_wavecal.png',
             takeaway='July 1998: 10 of 10 frames, 37 orders each; wavecal RMS medians 0.115–0.127 px.')
    d.figure('The traced orders and the flat', 'fig_p1_orders.png',
             takeaway='The inherited find_trim_edge = 3,3 would mask 6 of ~10 pixels per order.')

    # ---- Phase 2 ----------------------------------------------------------
    d.section('Phase 2', 'Twenty nights, and velocities from a lamp',
              'The whole discovery era reduced; velocities by cross-correlation; '
              'the inputs phase 3 needs.', color='8a8a86')
    d.bullets('What phase 2 built', [
        B('20 nights, 36 frames, 37 orders; wavecal RMS 0.11–0.15 px'),
        B('Quality filter: 1329 order-spectra, 11.3% rejected'),
        B('Template: three cell-out exposures, S/N ~790 per pixel'),
        B('Atlas: Fischer 2022 FTS; positions match (r = 0.928), depths need α = 2.59'),
        B('Adapter: observed frame, JD(UTC) mid-exposure, BVC in m/s'),
    ], takeaway='Plus refframe_audit.py: two PypeIt core/wave.py bugs (next slide).')
    d.bullets('PypeIt’s velocity correction (refframe_audit.py)', [
        B('Solar-term sign error in geomotion_velocity (wave.py:128)'),
        B('+9 to +14 m/s off astropy; drifts 5.2 m/s over nine months', level=1),
        B('heliocentric is the default: every user is affected', level=1),
        B('Relativistic terms omitted in geomotion_correct'),
        B('−4.6 m/s, nearly constant', level=1),
    ], takeaway='Both still in develop; reported upstream.')
    d.figure('The atlas: positions transfer, depths need α ≈ 2.6', 'fig_p2_atlas.png',
             takeaway='Beer–Lambert, not pyodine’s linear scaling (negative at α = 2.6).')
    d.figure('Cross-correlation: the planet is not there', 'fig_p2_phasefold.png',
             takeaway='{:d} epochs, rms {:.0f} m/s; K = 408 ± 188 m/s — not a detection.'.format(
                 N['n_xc'], N['xc_rms']))
    d.bullets('Why the lamp fails', [
        B('Orders within one exposure agree to 47 m/s'),
        B('Exposures disagree by ~700 m/s'),
        B('So the limit is the wavelength zero point'),
        B('Borrowed-arc night: +1.5 to +2.4 km/s off'),
        B('08-25: drifts 1.6 km/s in 6.7 hours'),
    ], takeaway='The iodine cell fixes exactly this: its ruler rides on the same photons.')

    # ---- Phase 3 ----------------------------------------------------------
    d.section('Phase 3', 'The iodine forward model',
              'Fork pyodine, adapt it to HIRES, fit every cell-in epoch, and assess '
              'exactly as phase 2 did.', color=BLUE)
    d.table('The pyodine fork: six tested changes', ['#', 'change', 'why'], [
        ['0', 'NumPy 2', 'does not run as shipped'],
        ['1', 'Beer–Lambert depth', 'linear goes negative'],
        ['2', 'atlas wavelength frame', 'air vs vacuum: 83 km/s'],
        ['3', 'bary units', 'JD(UTC) and m/s'],
        ['4', "weight by 'ivar'", 'use PypeIt’s noise'],
        ['5', 'chunk template index', 'order subsets misfit'],
    ], widths=[0.8, 5.4, 6.13], row_h=0.6,
        takeaway='pyodine 4488b09 + changes 0–5; each has a test that fails without it.')
    d.figure('Deconvolution: pyodine’s spline fails at HIRES sampling', 'fig_p3_deconv.png',
             takeaway='misc.rebin overshoots 2.2-px lines; oversampling 1 re-convolves at χ² 1.1.')
    d.figure('One epoch: right velocity, wrong iodine', 'fig_p5_one_epoch.png',
             takeaway='Within 12–18 m/s of prediction; the misfit tracks iodine contrast (ρ ≈ +0.7).')
    d.figure('The instrumental profile is not the lever', 'fig_p6_lsf_models.png',
             takeaway='Four LSF models tie to ±5%; super-Gaussian chosen.')
    d.figure('B stars: the atlas’s line pattern is the limit', 'fig_p6b_bstars.png',
             takeaway='HIRES cell α ≈ 3.33; fixing α per chunk buys nothing.')
    d.figure('All 31 epochs: the misfit is common, and cancels', 'fig_p7_epochs.png',
             takeaway='pyodine’s chunk offsets remove it: 290 → 230 m/s per chunk; ~19 m/s per epoch.')
    d.figure('The detection', 'fig_ph3_phasefold.png',
             takeaway='K = {:.1f} ± {:.1f} m/s ({:.1f}σ); residual {:.1f} m/s, χ²/dof 1.05.'.format(
                 N['K'], N['sK'], N['nsig'], N['resid']))
    d.figure('Epoch by epoch against the modern catalogue', 'fig_ph3_compare.png',
             takeaway='r = +0.89 (phase 2: +0.38); the errors are honest (χ²/dof 1.03).')
    d.figure('Residuals and the blind period search', 'fig_ph3_residuals.png',
             takeaway='No ThAr, misfit or order-count dependence; residual periodogram flat.')
    d.figure('Every named calibration defect is fixed', 'fig_p9_diagnosis.png',
             takeaway='Borrowed arcs, intra-night drift, the no-flat night, 09-13’s bad arc.')
    d.table('What is left: re-combining without the weakest data', ['variant', 'epochs', 'rms', 'K (m/s)'], [
        ['everything (the result)', '31', '{:.1f}'.format(N['var_base']),
         '{:.1f} ± {:.1f}'.format(N['K'], N['sK'])],
        ['tellurics masked', '31', '24.2', '73.0 ± 6.7'],
        ['no epochs with ≤ 8 orders', '25', '18.2', '70.8 ± 5.6'],
        ['no red orders 58–61', '31', '17.2', '72.4 ± 4.7'],
        ['both', '25', '{:.1f}'.format(N['var_best']),
         '{:.1f} ± {:.1f}'.format(N['K_best'], N['sK_best'])],
    ], widths=[5.9, 1.7, 1.7, 3.03], row_h=0.6,
        takeaway='K is stable (69.5–73.8). The 11.5 m/s variant was chosen after seeing residuals: '
                 'reported, not claimed.')
    d.figure('Where we stand', 'fig8_precision.png',
             takeaway='Photon budget 1.4 m/s; achieved 26 m/s. The gap is modelling, not photons.')

    # ---- Wrap-up ----------------------------------------------------------
    d.bullets('Why 26 m/s and not 3', [
        B('The atlas is a different cell: part of its misfit does not cancel'),
        B('Weak iodine in the red orders: errors shared by whole orders'),
        B('Six epochs with only 2–8 usable orders'),
        B('A simple instrumental profile (4-parameter super-Gaussian)'),
        B('Tellurics unmodelled; a marginal seasonal term'),
    ], takeaway='Largest single gain: the HIRES cell’s own FTS spectrum, if it exists.')
    d.bullets('Upstream reports', [
        B('PypeIt: 15 items (email to Ryan Cooke, issues, PR)'),
        B('keck_hires_orig bugs; silent failures of run_pypeit', level=1),
        B('wave.py sign error; ivar mis-scaled; zero wavelengths', level=1),
        B('pyodine: 21 items (GitHub issues)'),
        B('6 fork changes; index and order traps; swallowed errors', level=1),
    ])
    d.bullets('Next steps', [
        B('A HIRES-cell iodine spectrum: FTS scan, or empirical from B stars'),
        B('Weight whole orders, not just chunks, in the combination'),
        B('Fix PypeIt’s noise model (optimal vs boxcar)'),
        B('Diagnose 1998-09-13’s arc'),
    ])
    d.bullets('Reproducibility', [
        B('Every number from a script; every table in first_hires_exoplanet/data/'),
        B('PypeIt 2.0.2.dev1217+g017bece06; pyodine 4488b09 + fork'),
        B('Velocities: fit_all_epochs.py; assessment: figs_phase3.py'),
        B('Reports: claude_prompts/data_phase{1,2,3}_prompt.md'),
        B('This deck: make_slides.py'),
    ])

    d.save(out)


def main():
    p = argparse.ArgumentParser(description='Build the technical slide deck (phase 3, prompts 12-13)')
    p.add_argument('--out', type=str, default=OUT)
    build(p.parse_args().out)


if __name__ == '__main__':
    main()
